# ShopSmart- Ecommerce Project

In [1]:
# An e-commerce company, ShopSmart, wants to better understand the behaviour of visitors browsing its online store. 
# Every day, thousands of users navigate through product pages, spend varying amounts of time on the website, and interact differently with content. 
# Currently, the company is unable to accurately predict which visitors are likely to complete a purchase, resulting in inefficient marketing strategies and lost revenue opportunities.

# To address this challenge, the company has collected data from 12,330 individual user sessions over a period of one year. Each session represents a unique visitor to ensure unbiased insights, avoiding the influence of specific users, promotional campaigns, seasonal trends, or special events. 
# The dataset includes a mix of numerical and categorical features that capture detailed information about users’ browsing behaviour and interactions with the website.

# You are hired as a Machine Learning Engineer to build a predictive model that can determine whether a visitor is likely to make a purchase based on their session behaviour. 
# Your task involves performing exploratory data analysis (EDA), applying appropriate feature preprocessing and transformations, and developing a Decision Tree based classification model. Since the dataset is imbalanced, model performance must be evaluated using the F1 score, with a benchmark value of 0.55 used to assess the effectiveness of the solution.

# Note – Make use of pruning to improve the performance of Decision Tree Classifier.

In [33]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sklearn.impute import SimpleImputer
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [34]:
users=pd.read_csv("shop_smart_ecommerce.csv")
users.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [35]:
# Fix missing values
users.isnull().sum()
users["Month"].nunique()
#Therer are no null values, so no fixing required

10

In [36]:
# Encode the values that are categorical
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop="first", sparse_output=False)

encoded = ohe.fit_transform(users[["Month", "VisitorType"]])
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(["Month", "VisitorType"]))

users = pd.concat([users.drop(["Month", "VisitorType"], axis=1), encoded_df], axis=1)
users.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,Month_Feb,Month_Jul,Month_June,Month_Mar,Month_May,Month_Nov,Month_Oct,Month_Sep,VisitorType_Other,VisitorType_Returning_Visitor
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [38]:
#Scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X=users.drop(columns=["Revenue"])
y=users["Revenue"].astype(int)
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=42)

In [39]:
#Train the model
model=DecisionTreeClassifier(max_depth=6,              # prevents deep overfitting
    min_samples_leaf=30,      # smooths decision boundaries
    class_weight="balanced",  # handles imbalance
    random_state=42)
model.fit(Xtrain,ytrain)

ypred=model.predict(Xtest)

In [42]:
print("F1 score:", f1_score(ytest, ypred))

F1 score: 0.6356011183597391